spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/myDb
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

